#############################################################################
# Makefile for building: QPhysics
# Generated by qmake (2.01a) (Qt 4.7.0) on: Thu Jul 15 09:18:11 2010
# Project:  QPhysics.pro
# Template: subdirs
# Command: /home/jon/Data/Applications/QT_4.7.0-beta1/bin/qmake -spec /usr/local/Trolltech/Qt-4.7.0/mkspecs/linux-g++ -o Makefile QPhysics.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /home/jon/Data/Applications/QT_4.7.0-beta1/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src-Box2D \
		sub-src

src/Box2D/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/Box2D/ || $(MKDIR) src/Box2D/ 
	cd src/Box2D/ && $(QMAKE) /home/jon/Data/Programming/QPhysics/QPhysics/src/Box2D/Box2D.pro -spec /usr/local/Trolltech/Qt-4.7.0/mkspecs/linux-g++ -o $(MAKEFILE)
sub-src-Box2D-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/Box2D/ || $(MKDIR) src/Box2D/ 
	cd src/Box2D/ && $(QMAKE) /home/jon/Data/Programming/QPhysics/QPhysics/src/Box2D/Box2D.pro -spec /usr/local/Trolltech/Qt-4.7.0/mkspecs/linux-g++ -o $(MAKEFILE)
sub-src-Box2D: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE)
sub-src-Box2D-make_default-ordered: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE) 
sub-src-Box2D-make_default: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE) 
sub-src-Box2D-make_first-ordered: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE) first
sub-src-Box2D-make_first: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE) first
sub-src-Box2D-all-ordered: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE) all
sub-src-Box2D-all: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE) all
sub-src-Box2D-clean-ordered: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-Box2D-clean: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-Box2D-distclean-ordered: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-Box2D-distclean: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-Box2D-install_subtargets-ordered: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE) install
sub-src-Box2D-install_subtargets: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE) install
sub-src-Box2D-uninstall_subtargets-ordered: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-src-Box2D-uninstall_subtargets: src/Box2D/$(MAKEFILE) FORCE
	cd src/Box2D/ && $(MAKE) -f $(MAKEFILE) uninstall
src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/jon/Data/Programming/QPhysics/QPhysics/src/src.pro -spec /usr/local/Trolltech/Qt-4.7.0/mkspecs/linux-g++ -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/jon/Data/Programming/QPhysics/QPhysics/src/src.pro -spec /usr/local/Trolltech/Qt-4.7.0/mkspecs/linux-g++ -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default-ordered: src/$(MAKEFILE) sub-src-Box2D-make_default-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_default: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first-ordered: src/$(MAKEFILE) sub-src-Box2D-make_first-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-make_first: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all-ordered: src/$(MAKEFILE) sub-src-Box2D-all-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-all: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean-ordered: src/$(MAKEFILE) sub-src-Box2D-clean-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-clean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean-ordered: src/$(MAKEFILE) sub-src-Box2D-distclean-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-distclean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets-ordered: src/$(MAKEFILE) sub-src-Box2D-install_subtargets-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-install_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets-ordered: src/$(MAKEFILE) sub-src-Box2D-uninstall_subtargets-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-src-uninstall_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: QPhysics.pro  /usr/local/Trolltech/Qt-4.7.0/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.7.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.7.0/mkspecs/linux-g++ -o Makefile QPhysics.pro
/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.7.0/mkspecs/linux-g++ -o Makefile QPhysics.pro

qmake_all: sub-src-Box2D-qmake_all sub-src-qmake_all FORCE

make_default: sub-src-Box2D-make_default-ordered sub-src-make_default-ordered FORCE
make_first: sub-src-Box2D-make_first-ordered sub-src-make_first-ordered FORCE
all: sub-src-Box2D-all-ordered sub-src-all-ordered FORCE
clean: sub-src-Box2D-clean-ordered sub-src-clean-ordered FORCE
distclean: sub-src-Box2D-distclean-ordered sub-src-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-Box2D-install_subtargets-ordered sub-src-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-Box2D-uninstall_subtargets-ordered sub-src-uninstall_subtargets-ordered FORCE

sub-src-Box2D-check_ordered: src/Box2D/$(MAKEFILE)
	cd src/Box2D/ && $(MAKE) check
sub-src-check_ordered: src/$(MAKEFILE) sub-src-Box2D-check_ordered 
	cd src/ && $(MAKE) check
check: sub-src-Box2D-check_ordered sub-src-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

